// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=.js"
// @generated from file cellaflow/v1/common.proto (package cellaflow.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * StepStatus defines compile-time type-safe execution states for a step.
 *
 * @generated from enum cellaflow.v1.StepStatus
 */
export enum StepStatus {
  /**
   * @generated from enum value: STEP_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STEP_STATUS_RUNNING = 1;
   */
  RUNNING = 1,

  /**
   * @generated from enum value: STEP_STATUS_SUCCESS = 2;
   */
  SUCCESS = 2,

  /**
   * @generated from enum value: STEP_STATUS_FAILED = 3;
   */
  FAILED = 3,

  /**
   * @generated from enum value: STEP_STATUS_TIMER_SCHEDULED = 4;
   */
  TIMER_SCHEDULED = 4,

  /**
   * @generated from enum value: STEP_STATUS_TIMER_FIRED = 5;
   */
  TIMER_FIRED = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(StepStatus)
proto3.util.setEnumType(StepStatus, "cellaflow.v1.StepStatus", [
  { no: 0, name: "STEP_STATUS_UNSPECIFIED" },
  { no: 1, name: "STEP_STATUS_RUNNING" },
  { no: 2, name: "STEP_STATUS_SUCCESS" },
  { no: 3, name: "STEP_STATUS_FAILED" },
  { no: 4, name: "STEP_STATUS_TIMER_SCHEDULED" },
  { no: 5, name: "STEP_STATUS_TIMER_FIRED" },
]);

/**
 * StepResult represents the outcome of a single step in a workflow execution session.
 *
 * @generated from message cellaflow.v1.StepResult
 */
export class StepResult extends Message<StepResult> {
  /**
   * Optional to distinguish between explicit sequence 0 and unset/omitted values.
   * Validation: Must be greater than 0 during normal execution.
   *
   * @generated from field: optional uint64 sequence = 1;
   */
  sequence?: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Safe enum-typed status to prevent raw string errors (e.g. typos).
   *
   * @generated from field: cellaflow.v1.StepStatus status = 3;
   */
  status = StepStatus.UNSPECIFIED;

  /**
   * Output payload generated by this execution step.
   * Validation: Size must not exceed 4MB (4,194,304 bytes).
   *
   * @generated from field: bytes output_payload = 4;
   */
  outputPayload = new Uint8Array(0);

  /**
   * Unique idempotency key to prevent duplicate tool execution.
   * Validation: If specified, must not be empty.
   *
   * @generated from field: optional string idempotency_key = 5;
   */
  idempotencyKey?: string;

  /**
   * Deadline for the sleep operation, represented as a Unix timestamp in milliseconds.
   * Used when status is STEP_STATUS_TIMER_SCHEDULED.
   *
   * @generated from field: optional uint64 deadline_ms = 6;
   */
  deadlineMs?: bigint;

  /**
   * The sequence number of the originating TimerScheduled event.
   * Used when status is STEP_STATUS_TIMER_FIRED to explicitly pair events.
   *
   * @generated from field: optional uint64 source_sequence = 7;
   */
  sourceSequence?: bigint;

  constructor(data?: PartialMessage<StepResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.StepResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "enum", T: proto3.getEnumType(StepStatus) },
    { no: 4, name: "output_payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "deadline_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 7, name: "source_sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StepResult {
    return new StepResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StepResult {
    return new StepResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StepResult {
    return new StepResult().fromJsonString(jsonString, options);
  }

  static equals(a: StepResult | PlainMessage<StepResult> | undefined, b: StepResult | PlainMessage<StepResult> | undefined): boolean {
    return proto3.util.equals(StepResult, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.WorkflowDefinition
 */
export class WorkflowDefinition extends Message<WorkflowDefinition> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  constructor(data?: PartialMessage<WorkflowDefinition>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.WorkflowDefinition";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorkflowDefinition {
    return new WorkflowDefinition().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorkflowDefinition {
    return new WorkflowDefinition().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorkflowDefinition {
    return new WorkflowDefinition().fromJsonString(jsonString, options);
  }

  static equals(a: WorkflowDefinition | PlainMessage<WorkflowDefinition> | undefined, b: WorkflowDefinition | PlainMessage<WorkflowDefinition> | undefined): boolean {
    return proto3.util.equals(WorkflowDefinition, a, b);
  }
}

