// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=.js"
// @generated from file cellaflow/v1/idempotency.proto (package cellaflow.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { StepResult } from "./common_pb.js";

/**
 * Key construction scope used by SDKs during key auto-derivation.
 * The SDK uses this to prefix the opaque idempotency_key before sending it
 * to the engine. The engine never parses this — it is purely an SDK concern.
 *
 * @generated from enum cellaflow.v1.IdempotencyScope
 */
export enum IdempotencyScope {
  /**
   * @generated from enum value: SCOPE_UNSPECIFIED = 0;
   */
  SCOPE_UNSPECIFIED = 0,

  /**
   * Shared across all agents in the session (Default)
   *
   * @generated from enum value: SCOPE_SESSION_WIDE = 1;
   */
  SCOPE_SESSION_WIDE = 1,

  /**
   * Isolated to the executing agent
   *
   * @generated from enum value: SCOPE_AGENT_PRIVATE = 2;
   */
  SCOPE_AGENT_PRIVATE = 2,

  /**
   * Isolated to the specific superstep / node
   *
   * @generated from enum value: SCOPE_STEP_LOCAL = 3;
   */
  SCOPE_STEP_LOCAL = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(IdempotencyScope)
proto3.util.setEnumType(IdempotencyScope, "cellaflow.v1.IdempotencyScope", [
  { no: 0, name: "SCOPE_UNSPECIFIED" },
  { no: 1, name: "SCOPE_SESSION_WIDE" },
  { no: 2, name: "SCOPE_AGENT_PRIVATE" },
  { no: 3, name: "SCOPE_STEP_LOCAL" },
]);

/**
 * @generated from enum cellaflow.v1.CacheStatus
 */
export enum CacheStatus {
  /**
   * @generated from enum value: CACHE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Found in cache (or completed by in-flight worker)
   *
   * @generated from enum value: CACHE_STATUS_HIT = 1;
   */
  HIT = 1,

  /**
   * Miss & lease granted: caller should execute tool
   *
   * @generated from enum value: CACHE_STATUS_ACQUIRED = 2;
   */
  ACQUIRED = 2,

  /**
   * Miss & currently running by another worker
   *
   * @generated from enum value: CACHE_STATUS_IN_PROGRESS = 3;
   */
  IN_PROGRESS = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(CacheStatus)
proto3.util.setEnumType(CacheStatus, "cellaflow.v1.CacheStatus", [
  { no: 0, name: "CACHE_STATUS_UNSPECIFIED" },
  { no: 1, name: "CACHE_STATUS_HIT" },
  { no: 2, name: "CACHE_STATUS_ACQUIRED" },
  { no: 3, name: "CACHE_STATUS_IN_PROGRESS" },
]);

/**
 * @generated from enum cellaflow.v1.RenewFailureReason
 */
export enum RenewFailureReason {
  /**
   * @generated from enum value: RENEW_FAILURE_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Lease timed out before renewal arrived
   *
   * @generated from enum value: RENEW_FAILURE_REASON_EXPIRED = 1;
   */
  EXPIRED = 1,

  /**
   * A newer worker acquired a higher fencing token
   *
   * @generated from enum value: RENEW_FAILURE_REASON_SUPERSEDED = 2;
   */
  SUPERSEDED = 2,

  /**
   * Key does not exist or was deleted
   *
   * @generated from enum value: RENEW_FAILURE_REASON_NOT_FOUND = 3;
   */
  NOT_FOUND = 3,

  /**
   * Step was already committed by another worker
   *
   * @generated from enum value: RENEW_FAILURE_REASON_COMPLETED = 4;
   */
  COMPLETED = 4,

  /**
   * The lease hit its maximum total lifetime and was reclaimed.
   *
   * Distinct from EXPIRED: the holder kept renewing and is likely still running,
   * so it must learn the engine took the lease back rather than that its own
   * renewal lapsed.
   *
   * @generated from enum value: RENEW_FAILURE_REASON_MAX_LIFETIME_EXCEEDED = 5;
   */
  MAX_LIFETIME_EXCEEDED = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(RenewFailureReason)
proto3.util.setEnumType(RenewFailureReason, "cellaflow.v1.RenewFailureReason", [
  { no: 0, name: "RENEW_FAILURE_REASON_UNSPECIFIED" },
  { no: 1, name: "RENEW_FAILURE_REASON_EXPIRED" },
  { no: 2, name: "RENEW_FAILURE_REASON_SUPERSEDED" },
  { no: 3, name: "RENEW_FAILURE_REASON_NOT_FOUND" },
  { no: 4, name: "RENEW_FAILURE_REASON_COMPLETED" },
  { no: 5, name: "RENEW_FAILURE_REASON_MAX_LIFETIME_EXCEEDED" },
]);

/**
 * @generated from enum cellaflow.v1.IdempotencyCommitStatus
 */
export enum IdempotencyCommitStatus {
  /**
   * @generated from enum value: IDEMPOTENCY_COMMIT_UNSPECIFIED = 0;
   */
  IDEMPOTENCY_COMMIT_UNSPECIFIED = 0,

  /**
   * @generated from enum value: IDEMPOTENCY_COMMIT_COMMITTED = 1;
   */
  IDEMPOTENCY_COMMIT_COMMITTED = 1,

  /**
   * Idempotent retry of the commit call itself
   *
   * @generated from enum value: IDEMPOTENCY_COMMIT_ALREADY_COMMITTED = 2;
   */
  IDEMPOTENCY_COMMIT_ALREADY_COMMITTED = 2,

  /**
   * Fencing token invalid — caller was fenced out
   *
   * @generated from enum value: IDEMPOTENCY_COMMIT_STALE_LEASE_REJECTED = 3;
   */
  IDEMPOTENCY_COMMIT_STALE_LEASE_REJECTED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(IdempotencyCommitStatus)
proto3.util.setEnumType(IdempotencyCommitStatus, "cellaflow.v1.IdempotencyCommitStatus", [
  { no: 0, name: "IDEMPOTENCY_COMMIT_UNSPECIFIED" },
  { no: 1, name: "IDEMPOTENCY_COMMIT_COMMITTED" },
  { no: 2, name: "IDEMPOTENCY_COMMIT_ALREADY_COMMITTED" },
  { no: 3, name: "IDEMPOTENCY_COMMIT_STALE_LEASE_REJECTED" },
]);

/**
 * @generated from message cellaflow.v1.CheckCacheRequest
 */
export class CheckCacheRequest extends Message<CheckCacheRequest> {
  /**
   * Opaque caller-supplied label, carried for logging and diagnostics.
   *
   * Not parsed into the idempotency key: key derivation is an SDK concern and the
   * engine treats the key as opaque.
   *
   * @generated from field: string agent_id = 1;
   */
  agentId = "";

  /**
   * Fully formed, opaque composite key
   *
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey = "";

  /**
   * @generated from field: optional uint64 wait_timeout_ms = 3;
   */
  waitTimeoutMs?: bigint;

  /**
   * Crash-detection window; defaults to engine config
   *
   * @generated from field: optional uint64 lease_ttl_ms = 4;
   */
  leaseTtlMs?: bigint;

  /**
   * The session this check is being made on behalf of.
   *
   * The idempotency key is opaque to the engine and deliberately stays that way,
   * so the session cannot be recovered from it. Without this field the engine
   * cannot tell the caller where its session currently sits, which is what a
   * caller needs after a cache hit — see `current_sequence` on the response.
   *
   * Optional for wire compatibility: clients predating this field still work,
   * they simply receive no `current_sequence` back.
   *
   * @generated from field: optional string session_id = 5;
   */
  sessionId?: string;

  /**
   * The graph position this caller intends to write to.
   *
   * The engine already knows which session is asking (field 5) and where that
   * session has committed to (`latest_committed_sequence`). This supplies the
   * one missing input: where the caller is going. With all three, a lease that
   * would authorise a side effect at an already-committed position can be
   * refused *before* the side effect happens, rather than rejected at commit
   * time after the money has moved.
   *
   * Note this is the caller's *intended* position, not the response's
   * `current_sequence`, which reports where the session already sits.
   *
   * Optional for wire compatibility: clients that omit it keep the previous
   * behaviour and are still granted leases. Sending 0 is an error rather than
   * a synonym for "unset" -- sequences are 1-based, so 0 is never a position a
   * caller could legitimately intend to write.
   *
   * @generated from field: optional uint64 sequence = 6;
   */
  sequence?: bigint;

  constructor(data?: PartialMessage<CheckCacheRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.CheckCacheRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "agent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "wait_timeout_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 4, name: "lease_ttl_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 5, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CheckCacheRequest {
    return new CheckCacheRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CheckCacheRequest {
    return new CheckCacheRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CheckCacheRequest {
    return new CheckCacheRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CheckCacheRequest | PlainMessage<CheckCacheRequest> | undefined, b: CheckCacheRequest | PlainMessage<CheckCacheRequest> | undefined): boolean {
    return proto3.util.equals(CheckCacheRequest, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.CheckCacheResponse
 */
export class CheckCacheResponse extends Message<CheckCacheResponse> {
  /**
   * @generated from field: cellaflow.v1.CacheStatus status = 1;
   */
  status = CacheStatus.UNSPECIFIED;

  /**
   * @generated from field: optional cellaflow.v1.StepResult cached_result = 2;
   */
  cachedResult?: StepResult;

  /**
   * Present iff ACQUIRED
   *
   * @generated from field: optional uint64 fencing_token = 3;
   */
  fencingToken?: bigint;

  /**
   * Present iff ACQUIRED or IN_PROGRESS
   *
   * @generated from field: optional uint64 lease_expires_at_ms = 4;
   */
  leaseExpiresAtMs?: bigint;

  /**
   * Present iff ACQUIRED — caller MUST renew
   *
   * @generated from field: optional uint64 heartbeat_interval_ms = 5;
   */
  heartbeatIntervalMs?: bigint;

  /**
   * Present iff IN_PROGRESS and wait exhausted
   *
   * @generated from field: optional uint64 retry_after_ms = 6;
   */
  retryAfterMs?: bigint;

  /**
   * Present iff IN_PROGRESS (for distributed tracing)
   *
   * @generated from field: optional string current_holder_id = 7;
   */
  currentHolderId?: string;

  /**
   * The requested session's highest committed sequence, or 0 if it has
   * none. Present whenever `session_id` was supplied — on every status, not only
   * on HIT.
   *
   * A caller that takes a HIT returns without committing, so its local counter
   * advances while the session's does not, and its next commit fails the
   * ordering check one step after the real cause. This lets it re-align.
   *
   * Returned on ACQUIRED and IN_PROGRESS too because it costs one seek on a call
   * that already performs a storage transaction, and it lets a caller about to
   * execute confirm it is where it thinks it is.
   *
   * @generated from field: optional uint64 current_sequence = 8;
   */
  currentSequence?: bigint;

  constructor(data?: PartialMessage<CheckCacheResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.CheckCacheResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(CacheStatus) },
    { no: 2, name: "cached_result", kind: "message", T: StepResult, opt: true },
    { no: 3, name: "fencing_token", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 4, name: "lease_expires_at_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 5, name: "heartbeat_interval_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 6, name: "retry_after_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 7, name: "current_holder_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "current_sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CheckCacheResponse {
    return new CheckCacheResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CheckCacheResponse {
    return new CheckCacheResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CheckCacheResponse {
    return new CheckCacheResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CheckCacheResponse | PlainMessage<CheckCacheResponse> | undefined, b: CheckCacheResponse | PlainMessage<CheckCacheResponse> | undefined): boolean {
    return proto3.util.equals(CheckCacheResponse, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.RenewLeaseRequest
 */
export class RenewLeaseRequest extends Message<RenewLeaseRequest> {
  /**
   * @generated from field: string agent_id = 1;
   */
  agentId = "";

  /**
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey = "";

  /**
   * @generated from field: uint64 fencing_token = 3;
   */
  fencingToken = protoInt64.zero;

  /**
   * @generated from field: uint64 extend_ms = 4;
   */
  extendMs = protoInt64.zero;

  constructor(data?: PartialMessage<RenewLeaseRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.RenewLeaseRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "agent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "fencing_token", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "extend_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenewLeaseRequest {
    return new RenewLeaseRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenewLeaseRequest {
    return new RenewLeaseRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenewLeaseRequest {
    return new RenewLeaseRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RenewLeaseRequest | PlainMessage<RenewLeaseRequest> | undefined, b: RenewLeaseRequest | PlainMessage<RenewLeaseRequest> | undefined): boolean {
    return proto3.util.equals(RenewLeaseRequest, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.RenewLeaseResponse
 */
export class RenewLeaseResponse extends Message<RenewLeaseResponse> {
  /**
   * False => lease was reclaimed/completed; stop execution
   *
   * @generated from field: bool renewed = 1;
   */
  renewed = false;

  /**
   * Present iff renewed = true
   *
   * @generated from field: optional uint64 new_expires_at_ms = 2;
   */
  newExpiresAtMs?: bigint;

  /**
   * Present iff renewed = false
   *
   * @generated from field: optional cellaflow.v1.RenewFailureReason failure_reason = 3;
   */
  failureReason?: RenewFailureReason;

  constructor(data?: PartialMessage<RenewLeaseResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.RenewLeaseResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "renewed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "new_expires_at_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 3, name: "failure_reason", kind: "enum", T: proto3.getEnumType(RenewFailureReason), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenewLeaseResponse {
    return new RenewLeaseResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenewLeaseResponse {
    return new RenewLeaseResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenewLeaseResponse {
    return new RenewLeaseResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RenewLeaseResponse | PlainMessage<RenewLeaseResponse> | undefined, b: RenewLeaseResponse | PlainMessage<RenewLeaseResponse> | undefined): boolean {
    return proto3.util.equals(RenewLeaseResponse, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.ReleaseLeaseRequest
 */
export class ReleaseLeaseRequest extends Message<ReleaseLeaseRequest> {
  /**
   * @generated from field: string agent_id = 1;
   */
  agentId = "";

  /**
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey = "";

  /**
   * @generated from field: uint64 fencing_token = 3;
   */
  fencingToken = protoInt64.zero;

  /**
   * e.g. "RATE_LIMITED_429", "CANCELLED", "TOOL_ERROR"
   *
   * @generated from field: optional string reason = 4;
   */
  reason?: string;

  constructor(data?: PartialMessage<ReleaseLeaseRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.ReleaseLeaseRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "agent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "fencing_token", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReleaseLeaseRequest {
    return new ReleaseLeaseRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReleaseLeaseRequest {
    return new ReleaseLeaseRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReleaseLeaseRequest {
    return new ReleaseLeaseRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReleaseLeaseRequest | PlainMessage<ReleaseLeaseRequest> | undefined, b: ReleaseLeaseRequest | PlainMessage<ReleaseLeaseRequest> | undefined): boolean {
    return proto3.util.equals(ReleaseLeaseRequest, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.ReleaseLeaseResponse
 */
export class ReleaseLeaseResponse extends Message<ReleaseLeaseResponse> {
  /**
   * @generated from field: bool released = 1;
   */
  released = false;

  constructor(data?: PartialMessage<ReleaseLeaseResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.ReleaseLeaseResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "released", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReleaseLeaseResponse {
    return new ReleaseLeaseResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReleaseLeaseResponse {
    return new ReleaseLeaseResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReleaseLeaseResponse {
    return new ReleaseLeaseResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReleaseLeaseResponse | PlainMessage<ReleaseLeaseResponse> | undefined, b: ReleaseLeaseResponse | PlainMessage<ReleaseLeaseResponse> | undefined): boolean {
    return proto3.util.equals(ReleaseLeaseResponse, a, b);
  }
}

