// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=.js"
// @generated from file cellaflow/v1/internal.proto (package cellaflow.v1.internal, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { StepResult } from "./common_pb.js";

/**
 * Internal storage record persisted in RocksDB's idempotency_cache Column Family.
 * Not exposed via gRPC — used only for serialization/deserialization within the engine.
 *
 * @generated from message cellaflow.v1.internal.CacheRecord
 */
export class CacheRecord extends Message<CacheRecord> {
  /**
   * @generated from oneof cellaflow.v1.internal.CacheRecord.record
   */
  record: {
    /**
     * @generated from field: cellaflow.v1.internal.LeaseRecord leased = 1;
     */
    value: LeaseRecord;
    case: "leased";
  } | {
    /**
     * @generated from field: cellaflow.v1.internal.CompletedRecord completed = 2;
     */
    value: CompletedRecord;
    case: "completed";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<CacheRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.internal.CacheRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "leased", kind: "message", T: LeaseRecord, oneof: "record" },
    { no: 2, name: "completed", kind: "message", T: CompletedRecord, oneof: "record" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CacheRecord {
    return new CacheRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CacheRecord {
    return new CacheRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CacheRecord {
    return new CacheRecord().fromJsonString(jsonString, options);
  }

  static equals(a: CacheRecord | PlainMessage<CacheRecord> | undefined, b: CacheRecord | PlainMessage<CacheRecord> | undefined): boolean {
    return proto3.util.equals(CacheRecord, a, b);
  }
}

/**
 * Represents an active lease held by a worker executing a tool.
 *
 * @generated from message cellaflow.v1.internal.LeaseRecord
 */
export class LeaseRecord extends Message<LeaseRecord> {
  /**
   * Global monotonic microsecond epoch timestamp
   *
   * @generated from field: uint64 fencing_token = 1;
   */
  fencingToken = protoInt64.zero;

  /**
   * Opaque per-attempt identifier for observability
   *
   * @generated from field: string holder_id = 2;
   */
  holderId = "";

  /**
   * When the lease was acquired (epoch ms)
   *
   * @generated from field: uint64 acquired_at_ms = 3;
   */
  acquiredAtMs = protoInt64.zero;

  /**
   * When the lease expires if not renewed (epoch ms)
   *
   * @generated from field: uint64 expires_at_ms = 4;
   */
  expiresAtMs = protoInt64.zero;

  /**
   * the graph position this lease claimed, if the caller declared one.
   *
   * Carried on the lease rather than passed to release_lease / commit_result so
   * that clearing the claim is a consequence of releasing the lease rather than
   * a parameter a caller could get wrong or forget. It also makes "claim and
   * lease lifetimes are equal" true by construction: the coordinates cannot
   * outlive the record holding them.
   *
   * Empty on a lease acquired without a declared position — nothing to clear.
   *
   * @generated from field: string claimed_session_id = 5;
   */
  claimedSessionId = "";

  /**
   * @generated from field: uint64 claimed_sequence = 6;
   */
  claimedSequence = protoInt64.zero;

  /**
   * The wall-clock ceiling on this lease, independent of renewals. Past it the
   * lease is reclaimable however recently it was renewed, which bounds how long a
   * holder can hold a position.
   *
   * Computed once at acquisition. A value of 0 means no ceiling.
   *
   * @generated from field: uint64 hard_expires_at_ms = 7;
   */
  hardExpiresAtMs = protoInt64.zero;

  constructor(data?: PartialMessage<LeaseRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.internal.LeaseRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "fencing_token", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "holder_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "acquired_at_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "expires_at_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "claimed_session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "claimed_sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "hard_expires_at_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LeaseRecord {
    return new LeaseRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LeaseRecord {
    return new LeaseRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LeaseRecord {
    return new LeaseRecord().fromJsonString(jsonString, options);
  }

  static equals(a: LeaseRecord | PlainMessage<LeaseRecord> | undefined, b: LeaseRecord | PlainMessage<LeaseRecord> | undefined): boolean {
    return proto3.util.equals(LeaseRecord, a, b);
  }
}

/**
 * Records which idempotency key currently owns a graph position.
 *
 * Stored in its own `sequence_claims` column family, keyed by
 * `<session_id>:<sequence padded to 20>`. Session ids are validated to contain no
 * colons, so the key parses unambiguously.
 *
 * @generated from message cellaflow.v1.internal.SequenceClaimRecord
 */
export class SequenceClaimRecord extends Message<SequenceClaimRecord> {
  /**
   * Who owns the position
   *
   * @generated from field: string idempotency_key = 1;
   */
  idempotencyKey = "";

  /**
   * The lease that created this claim
   *
   * @generated from field: uint64 fencing_token = 2;
   */
  fencingToken = protoInt64.zero;

  /**
   * Opaque per-attempt id, for diagnostics
   *
   * @generated from field: string holder_id = 3;
   */
  holderId = "";

  /**
   * Advisory: the lease's expiry when this claim was written. Renewal extends the
   * lease without rewriting the claim, so liveness is read from the owning lease
   * record. Kept for diagnostics and for the refusal message.
   *
   * @generated from field: uint64 expires_at_ms = 4;
   */
  expiresAtMs = protoInt64.zero;

  constructor(data?: PartialMessage<SequenceClaimRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.internal.SequenceClaimRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "fencing_token", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "holder_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "expires_at_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SequenceClaimRecord {
    return new SequenceClaimRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SequenceClaimRecord {
    return new SequenceClaimRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SequenceClaimRecord {
    return new SequenceClaimRecord().fromJsonString(jsonString, options);
  }

  static equals(a: SequenceClaimRecord | PlainMessage<SequenceClaimRecord> | undefined, b: SequenceClaimRecord | PlainMessage<SequenceClaimRecord> | undefined): boolean {
    return proto3.util.equals(SequenceClaimRecord, a, b);
  }
}

/**
 * Represents a completed tool execution result cached for idempotency.
 *
 * @generated from message cellaflow.v1.internal.CompletedRecord
 */
export class CompletedRecord extends Message<CompletedRecord> {
  /**
   * @generated from field: cellaflow.v1.StepResult result = 1;
   */
  result?: StepResult;

  /**
   * When the result was committed (epoch ms)
   *
   * @generated from field: uint64 completed_at_ms = 2;
   */
  completedAtMs = protoInt64.zero;

  /**
   * The fencing token held by the worker that committed this result.
   *
   * Without it, once a key transitions to Completed the token that completed it
   * was discarded, so a later caller's token had nothing to be validated against
   * and a superseded worker received a success response. Records written before
   * this field existed decode as 0, which is treated as "unknown, skip
   * validation" — tokens are monotonic epoch-microsecond values and are never
   * legitimately 0.
   *
   * @generated from field: uint64 fencing_token = 3;
   */
  fencingToken = protoInt64.zero;

  /**
   * The graph sequence this result was journaled at.
   *
   * An AlreadyCommitted outcome only implies a durable event exists at *that*
   * sequence. A caller committing the same key at a different position has no
   * event backing it, so letting the actor advance its sequence would leave
   * in-memory state ahead of the durable log. Same reasoning as the field above:
   * 0 means a legacy record with no recorded sequence.
   *
   * @generated from field: uint64 committed_sequence = 4;
   */
  committedSequence = protoInt64.zero;

  constructor(data?: PartialMessage<CompletedRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.internal.CompletedRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "message", T: StepResult },
    { no: 2, name: "completed_at_ms", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "fencing_token", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "committed_sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompletedRecord {
    return new CompletedRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompletedRecord {
    return new CompletedRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompletedRecord {
    return new CompletedRecord().fromJsonString(jsonString, options);
  }

  static equals(a: CompletedRecord | PlainMessage<CompletedRecord> | undefined, b: CompletedRecord | PlainMessage<CompletedRecord> | undefined): boolean {
    return proto3.util.equals(CompletedRecord, a, b);
  }
}

