// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=.js"
// @generated from file cellaflow/v1/service.proto (package cellaflow.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CommitStepRequest, CommitStepResponse, GetGraphRequest, GetGraphResponse, StartSessionRequest, StartSessionResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { CheckCacheRequest, CheckCacheResponse, ReleaseLeaseRequest, ReleaseLeaseResponse, RenewLeaseRequest, RenewLeaseResponse } from "./idempotency_pb.js";

/**
 * @generated from service cellaflow.v1.WorkflowEngineService
 */
export const WorkflowEngineService = {
  typeName: "cellaflow.v1.WorkflowEngineService",
  methods: {
    /**
     * Starts a new workflow execution session.
     * Concurrency Guard: If the client proposes a custom `session_id` inside StartSessionRequest,
     * the engine MUST perform transactional check-and-insert to prevent concurrent race conditions
     * that would result in double-initialization or state overwriting.
     *
     * @generated from rpc cellaflow.v1.WorkflowEngineService.StartSession
     */
    startSession: {
      name: "StartSession",
      I: StartSessionRequest,
      O: StartSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Commits the result of an execution step (Cognitive Graph event).
     * Ordering Guard: The engine MUST validate that `step_result.sequence` matches the expected
     * next sequence number (i.e. expected = current_sequence + 1).
     * Concurrency Guard: The write transaction MUST perform an optimistic concurrency check
     * comparing expected vs actual current sequence to fail gracefully in case of race conditions.
     *
     * @generated from rpc cellaflow.v1.WorkflowEngineService.CommitStep
     */
    commitStep: {
      name: "CommitStep",
      I: CommitStepRequest,
      O: CommitStepResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves the Cognitive Graph history (sequence of steps) for a session.
     * Pagination Guard: GetGraphResponse is paginated. The implementation must enforce a default
     * pagination limit (e.g. 100) and a maximum pagination limit (e.g. 1000) to prevent OOM errors
     * on large graph histories.
     *
     * @generated from rpc cellaflow.v1.WorkflowEngineService.GetGraph
     */
    getGraph: {
      name: "GetGraph",
      I: GetGraphRequest,
      O: GetGraphResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Idempotency cache RPCs
     *
     * @generated from rpc cellaflow.v1.WorkflowEngineService.CheckIdempotencyCache
     */
    checkIdempotencyCache: {
      name: "CheckIdempotencyCache",
      I: CheckCacheRequest,
      O: CheckCacheResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cellaflow.v1.WorkflowEngineService.RenewLease
     */
    renewLease: {
      name: "RenewLease",
      I: RenewLeaseRequest,
      O: RenewLeaseResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cellaflow.v1.WorkflowEngineService.ReleaseLease
     */
    releaseLease: {
      name: "ReleaseLease",
      I: ReleaseLeaseRequest,
      O: ReleaseLeaseResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

