// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=.js"
// @generated from file cellaflow/v1/service.proto (package cellaflow.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { StepResult } from "./common_pb.js";
import { IdempotencyCommitStatus } from "./idempotency_pb.js";

/**
 * @generated from message cellaflow.v1.StartSessionRequest
 */
export class StartSessionRequest extends Message<StartSessionRequest> {
  /**
   * @generated from field: string workflow_id = 1;
   */
  workflowId = "";

  /**
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * Optional client-proposed session identifier.
   *
   * @generated from field: optional string session_id = 3;
   */
  sessionId?: string;

  constructor(data?: PartialMessage<StartSessionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.StartSessionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "workflow_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartSessionRequest {
    return new StartSessionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartSessionRequest {
    return new StartSessionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartSessionRequest {
    return new StartSessionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartSessionRequest | PlainMessage<StartSessionRequest> | undefined, b: StartSessionRequest | PlainMessage<StartSessionRequest> | undefined): boolean {
    return proto3.util.equals(StartSessionRequest, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.StartSessionResponse
 */
export class StartSessionResponse extends Message<StartSessionResponse> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * @generated from field: bool is_recovered = 3;
   */
  isRecovered = false;

  constructor(data?: PartialMessage<StartSessionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.StartSessionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "is_recovered", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartSessionResponse {
    return new StartSessionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartSessionResponse {
    return new StartSessionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartSessionResponse {
    return new StartSessionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartSessionResponse | PlainMessage<StartSessionResponse> | undefined, b: StartSessionResponse | PlainMessage<StartSessionResponse> | undefined): boolean {
    return proto3.util.equals(StartSessionResponse, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.CommitStepRequest
 */
export class CommitStepRequest extends Message<CommitStepRequest> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: cellaflow.v1.StepResult step_result = 2;
   */
  stepResult?: StepResult;

  /**
   * Idempotency lease validation fields
   *
   * @generated from field: optional string idempotency_key = 10;
   */
  idempotencyKey?: string;

  /**
   * Required whenever idempotency_key is set
   *
   * @generated from field: optional uint64 idempotency_fencing_token = 11;
   */
  idempotencyFencingToken?: bigint;

  constructor(data?: PartialMessage<CommitStepRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.CommitStepRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "step_result", kind: "message", T: StepResult },
    { no: 10, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "idempotency_fencing_token", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CommitStepRequest {
    return new CommitStepRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CommitStepRequest {
    return new CommitStepRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CommitStepRequest {
    return new CommitStepRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CommitStepRequest | PlainMessage<CommitStepRequest> | undefined, b: CommitStepRequest | PlainMessage<CommitStepRequest> | undefined): boolean {
    return proto3.util.equals(CommitStepRequest, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.CommitStepResponse
 */
export class CommitStepResponse extends Message<CommitStepResponse> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: uint64 next_sequence = 2;
   */
  nextSequence = protoInt64.zero;

  /**
   * @generated from field: optional cellaflow.v1.IdempotencyCommitStatus idempotency_status = 5;
   */
  idempotencyStatus?: IdempotencyCommitStatus;

  constructor(data?: PartialMessage<CommitStepResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.CommitStepResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "next_sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "idempotency_status", kind: "enum", T: proto3.getEnumType(IdempotencyCommitStatus), opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CommitStepResponse {
    return new CommitStepResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CommitStepResponse {
    return new CommitStepResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CommitStepResponse {
    return new CommitStepResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CommitStepResponse | PlainMessage<CommitStepResponse> | undefined, b: CommitStepResponse | PlainMessage<CommitStepResponse> | undefined): boolean {
    return proto3.util.equals(CommitStepResponse, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.GetGraphRequest
 */
export class GetGraphRequest extends Message<GetGraphRequest> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * Maximum number of items to retrieve in a single page.
   * Enforced limits: Default = 100, Max = 1000.
   *
   * @generated from field: optional uint32 limit = 2;
   */
  limit?: number;

  /**
   * Cursor for pagination token.
   *
   * @generated from field: optional string cursor = 3;
   */
  cursor?: string;

  constructor(data?: PartialMessage<GetGraphRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.GetGraphRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 3, name: "cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGraphRequest {
    return new GetGraphRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGraphRequest {
    return new GetGraphRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGraphRequest {
    return new GetGraphRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetGraphRequest | PlainMessage<GetGraphRequest> | undefined, b: GetGraphRequest | PlainMessage<GetGraphRequest> | undefined): boolean {
    return proto3.util.equals(GetGraphRequest, a, b);
  }
}

/**
 * @generated from message cellaflow.v1.GetGraphResponse
 */
export class GetGraphResponse extends Message<GetGraphResponse> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: repeated cellaflow.v1.StepResult steps = 2;
   */
  steps: StepResult[] = [];

  /**
   * Token for fetching the next page, or empty if there are no more pages.
   *
   * @generated from field: optional string next_cursor = 3;
   */
  nextCursor?: string;

  constructor(data?: PartialMessage<GetGraphResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cellaflow.v1.GetGraphResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "steps", kind: "message", T: StepResult, repeated: true },
    { no: 3, name: "next_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGraphResponse {
    return new GetGraphResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGraphResponse {
    return new GetGraphResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGraphResponse {
    return new GetGraphResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetGraphResponse | PlainMessage<GetGraphResponse> | undefined, b: GetGraphResponse | PlainMessage<GetGraphResponse> | undefined): boolean {
    return proto3.util.equals(GetGraphResponse, a, b);
  }
}

