#!/bin/bash
set -e

# Get the directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_DIR="$(dirname "$SCRIPT_DIR")"
ROOT_DIR="$(dirname "$PYTHON_DIR")"

echo "Generating protobufs using grpcio-tools..."

# Ensure grpcio-tools is installed in the local environment, or it will fail
python3 -m grpc_tools.protoc \
    -I"$ROOT_DIR/proto" \
    --python_out="$PYTHON_DIR/src" \
    --grpc_python_out="$PYTHON_DIR/src" \
    "$ROOT_DIR"/proto/cellaflow/v1/*.proto

# Fix relative imports generated by protoc for python
if [ "$(uname)" = "Darwin" ]; then
    sed -i '' -E 's/from cellaflow.v1 import (.*_pb2) as/from . import \1 as/g' "$PYTHON_DIR"/src/cellaflow/v1/*_pb2*.py
else
    sed -i -E 's/from cellaflow.v1 import (.*_pb2) as/from . import \1 as/g' "$PYTHON_DIR"/src/cellaflow/v1/*_pb2*.py
fi

echo "Protobufs generated successfully in python/src."
