# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cellaflow/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cellaflow/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63\x65llaflow/v1/common.proto\x12\x0c\x63\x65llaflow.v1\"\x8e\x02\n\nStepResult\x12\x15\n\x08sequence\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x0c\n\x04name\x18\x02 \x01(\t\x12(\n\x06status\x18\x03 \x01(\x0e\x32\x18.cellaflow.v1.StepStatus\x12\x16\n\x0eoutput_payload\x18\x04 \x01(\x0c\x12\x1c\n\x0fidempotency_key\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65\x61\x64line_ms\x18\x06 \x01(\x04H\x02\x88\x01\x01\x12\x1c\n\x0fsource_sequence\x18\x07 \x01(\x04H\x03\x88\x01\x01\x42\x0b\n\t_sequenceB\x12\n\x10_idempotency_keyB\x0e\n\x0c_deadline_msB\x12\n\x10_source_sequence\"F\n\x12WorkflowDefinition\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t*\xb1\x01\n\nStepStatus\x12\x1b\n\x17STEP_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13STEP_STATUS_RUNNING\x10\x01\x12\x17\n\x13STEP_STATUS_SUCCESS\x10\x02\x12\x16\n\x12STEP_STATUS_FAILED\x10\x03\x12\x1f\n\x1bSTEP_STATUS_TIMER_SCHEDULED\x10\x04\x12\x1b\n\x17STEP_STATUS_TIMER_FIRED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cellaflow.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STEPSTATUS']._serialized_start=389
  _globals['_STEPSTATUS']._serialized_end=566
  _globals['_STEPRESULT']._serialized_start=44
  _globals['_STEPRESULT']._serialized_end=314
  _globals['_WORKFLOWDEFINITION']._serialized_start=316
  _globals['_WORKFLOWDEFINITION']._serialized_end=386
# @@protoc_insertion_point(module_scope)
