# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cellaflow/v1/internal.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cellaflow/v1/internal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as cellaflow_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63\x65llaflow/v1/internal.proto\x12\x15\x63\x65llaflow.v1.internal\x1a\x19\x63\x65llaflow/v1/common.proto\"\x8a\x01\n\x0b\x43\x61\x63heRecord\x12\x34\n\x06leased\x18\x01 \x01(\x0b\x32\".cellaflow.v1.internal.LeaseRecordH\x00\x12;\n\tcompleted\x18\x02 \x01(\x0b\x32&.cellaflow.v1.internal.CompletedRecordH\x00\x42\x08\n\x06record\"f\n\x0bLeaseRecord\x12\x15\n\rfencing_token\x18\x01 \x01(\x04\x12\x11\n\tholder_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63quired_at_ms\x18\x03 \x01(\x04\x12\x15\n\rexpires_at_ms\x18\x04 \x01(\x04\"T\n\x0f\x43ompletedRecord\x12(\n\x06result\x18\x01 \x01(\x0b\x32\x18.cellaflow.v1.StepResult\x12\x17\n\x0f\x63ompleted_at_ms\x18\x02 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cellaflow.v1.internal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CACHERECORD']._serialized_start=82
  _globals['_CACHERECORD']._serialized_end=220
  _globals['_LEASERECORD']._serialized_start=222
  _globals['_LEASERECORD']._serialized_end=324
  _globals['_COMPLETEDRECORD']._serialized_start=326
  _globals['_COMPLETEDRECORD']._serialized_end=410
# @@protoc_insertion_point(module_scope)
