# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import idempotency_pb2 as cellaflow_dot_v1_dot_idempotency__pb2
from . import service_pb2 as cellaflow_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cellaflow/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowEngineServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/cellaflow.v1.WorkflowEngineService/StartSession',
                request_serializer=cellaflow_dot_v1_dot_service__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=cellaflow_dot_v1_dot_service__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.CommitStep = channel.unary_unary(
                '/cellaflow.v1.WorkflowEngineService/CommitStep',
                request_serializer=cellaflow_dot_v1_dot_service__pb2.CommitStepRequest.SerializeToString,
                response_deserializer=cellaflow_dot_v1_dot_service__pb2.CommitStepResponse.FromString,
                _registered_method=True)
        self.GetGraph = channel.unary_unary(
                '/cellaflow.v1.WorkflowEngineService/GetGraph',
                request_serializer=cellaflow_dot_v1_dot_service__pb2.GetGraphRequest.SerializeToString,
                response_deserializer=cellaflow_dot_v1_dot_service__pb2.GetGraphResponse.FromString,
                _registered_method=True)
        self.CheckIdempotencyCache = channel.unary_unary(
                '/cellaflow.v1.WorkflowEngineService/CheckIdempotencyCache',
                request_serializer=cellaflow_dot_v1_dot_idempotency__pb2.CheckCacheRequest.SerializeToString,
                response_deserializer=cellaflow_dot_v1_dot_idempotency__pb2.CheckCacheResponse.FromString,
                _registered_method=True)
        self.RenewLease = channel.unary_unary(
                '/cellaflow.v1.WorkflowEngineService/RenewLease',
                request_serializer=cellaflow_dot_v1_dot_idempotency__pb2.RenewLeaseRequest.SerializeToString,
                response_deserializer=cellaflow_dot_v1_dot_idempotency__pb2.RenewLeaseResponse.FromString,
                _registered_method=True)
        self.ReleaseLease = channel.unary_unary(
                '/cellaflow.v1.WorkflowEngineService/ReleaseLease',
                request_serializer=cellaflow_dot_v1_dot_idempotency__pb2.ReleaseLeaseRequest.SerializeToString,
                response_deserializer=cellaflow_dot_v1_dot_idempotency__pb2.ReleaseLeaseResponse.FromString,
                _registered_method=True)


class WorkflowEngineServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartSession(self, request, context):
        """Starts a new workflow execution session.
        Concurrency Guard: If the client proposes a custom `session_id` inside StartSessionRequest,
        the engine MUST perform transactional check-and-insert to prevent concurrent race conditions
        that would result in double-initialization or state overwriting.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitStep(self, request, context):
        """Commits the result of an execution step (Cognitive Graph event).
        Ordering Guard: The engine MUST validate that `step_result.sequence` matches the expected
        next sequence number (i.e. expected = current_sequence + 1).
        Concurrency Guard: The write transaction MUST perform an optimistic concurrency check
        comparing expected vs actual current sequence to fail gracefully in case of race conditions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraph(self, request, context):
        """Retrieves the Cognitive Graph history (sequence of steps) for a session.
        Pagination Guard: GetGraphResponse is paginated. The implementation must enforce a default
        pagination limit (e.g. 100) and a maximum pagination limit (e.g. 1000) to prevent OOM errors
        on large graph histories.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIdempotencyCache(self, request, context):
        """Idempotency cache RPCs (CEL-30)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=cellaflow_dot_v1_dot_service__pb2.StartSessionRequest.FromString,
                    response_serializer=cellaflow_dot_v1_dot_service__pb2.StartSessionResponse.SerializeToString,
            ),
            'CommitStep': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitStep,
                    request_deserializer=cellaflow_dot_v1_dot_service__pb2.CommitStepRequest.FromString,
                    response_serializer=cellaflow_dot_v1_dot_service__pb2.CommitStepResponse.SerializeToString,
            ),
            'GetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraph,
                    request_deserializer=cellaflow_dot_v1_dot_service__pb2.GetGraphRequest.FromString,
                    response_serializer=cellaflow_dot_v1_dot_service__pb2.GetGraphResponse.SerializeToString,
            ),
            'CheckIdempotencyCache': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIdempotencyCache,
                    request_deserializer=cellaflow_dot_v1_dot_idempotency__pb2.CheckCacheRequest.FromString,
                    response_serializer=cellaflow_dot_v1_dot_idempotency__pb2.CheckCacheResponse.SerializeToString,
            ),
            'RenewLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLease,
                    request_deserializer=cellaflow_dot_v1_dot_idempotency__pb2.RenewLeaseRequest.FromString,
                    response_serializer=cellaflow_dot_v1_dot_idempotency__pb2.RenewLeaseResponse.SerializeToString,
            ),
            'ReleaseLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLease,
                    request_deserializer=cellaflow_dot_v1_dot_idempotency__pb2.ReleaseLeaseRequest.FromString,
                    response_serializer=cellaflow_dot_v1_dot_idempotency__pb2.ReleaseLeaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cellaflow.v1.WorkflowEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cellaflow.v1.WorkflowEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowEngineService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cellaflow.v1.WorkflowEngineService/StartSession',
            cellaflow_dot_v1_dot_service__pb2.StartSessionRequest.SerializeToString,
            cellaflow_dot_v1_dot_service__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cellaflow.v1.WorkflowEngineService/CommitStep',
            cellaflow_dot_v1_dot_service__pb2.CommitStepRequest.SerializeToString,
            cellaflow_dot_v1_dot_service__pb2.CommitStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cellaflow.v1.WorkflowEngineService/GetGraph',
            cellaflow_dot_v1_dot_service__pb2.GetGraphRequest.SerializeToString,
            cellaflow_dot_v1_dot_service__pb2.GetGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckIdempotencyCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cellaflow.v1.WorkflowEngineService/CheckIdempotencyCache',
            cellaflow_dot_v1_dot_idempotency__pb2.CheckCacheRequest.SerializeToString,
            cellaflow_dot_v1_dot_idempotency__pb2.CheckCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cellaflow.v1.WorkflowEngineService/RenewLease',
            cellaflow_dot_v1_dot_idempotency__pb2.RenewLeaseRequest.SerializeToString,
            cellaflow_dot_v1_dot_idempotency__pb2.RenewLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cellaflow.v1.WorkflowEngineService/ReleaseLease',
            cellaflow_dot_v1_dot_idempotency__pb2.ReleaseLeaseRequest.SerializeToString,
            cellaflow_dot_v1_dot_idempotency__pb2.ReleaseLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
